@baseUrl = http://localhost:3333

###
POST {{baseUrl}}/credentials/auth
Content-Type: application/json

{
  "cpf": "05399970210",
  "password": "node-20"
}

###
POST {{baseUrl}}/students
Content-Type: application/json

{
    "username": "John Doe",
    "cpf": "000.000.000-00",
    "password": "node-20",
    "email": "johndoe@acne.com",
    "birthday": "01/01/2002",
    "civilId": 12345,
    "courseId": "clz1f0f2v000013hh4mwb399j",
    "poleId": "clz1f0xk4000113hhfg6euud4"
}

###
PUT {{baseUrl}}/students/clza1ixu40001jbjg0jsegv4q
Authorization: Bearer 
Content-Type: application/json

{
  "username": "Jenny Doe"
}

###
POST {{baseUrl}}/disciplines/clzy42e4p0005rn3lv4n60xa9/assessment
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7InN1YiI6ImNsenkydWFmMzAwMDNybjNsN3pkNHdxNXYiLCJyb2xlIjoiZGV2In0sImlhdCI6MTcyMzg5NzM1MywiZXhwIjoxNzIzOTAwOTUzfQ.Aa6yHsyY2I1gQunFuWc4vh1icqmKXBCP0SM5WxSX-mA
Content-Type: application/json

{
  "courseId": "clzy2q0vr0000rn3lh46bujpf",
  "studentId": "clzy2scec0002rn3lc2qiz7yy",
  "vf": 6
}