services:
  postgres:
    container_name: boletim
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=boletims

  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_HOST=127.0.0.1
      - REDIS_PORT=6379
    ports:
      - "6379:6379"